<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PmbCamabas extends Model
{
    protected $fillable = [
        'fullname',
        'gender',
        'place_of_birth',
        'birthday',
        'blood_group',
        'riwayat_penyakit',
        'nomor_wa',
        'email',
        'id_line',
        'alamat',
        'kota_kab',
        'daerah',
        'desa',
        'kelompok',
        'wa_pengurus',
        'universitas',
        'jurusan',
        'motivasi',
        'mondok_asal',
        'muballigh',
        'foto_pas',
        'nama_ayah',
        'profesi_ayah',
        'nama_ibu',
        'profesi_ibu',
        'nama_wali',
        'profesi_wali',
        'alamat_ortu_wali',
        'nomor_wa_ortu_wali',
        'seleksi_luring',
        'alasan_seleksi_daring',
        'tanggal_seleksi',
        'pendamping_seleksi',
        'angkatan',
        'status',
        'catatan_khusus',
        'nilai_bacaan',
        'nilai_bacaan_ket',
        'nilai_bacaan_mentor',
        'nilai_penyampaian_quran',
        'nilai_penyampaian_quran_ket',
        'nilai_penyampaian_quran_mentor',
        'nilai_adzan',
        'nilai_adzan_ket',
        'nilai_adzan_mentor',
        'nilai_pegon',
        'nilai_pegon_ket',
        'nilai_pegon_mentor',
        'nilai_wawancara',
        'nilai_wawancara_ket',
        'nilai_wawancara_mentor',
    ];
}
